# Exercice  semaine 1- data science
- Date limite de soumission des réponses: Jeudi 23 mars 2023 à 12h

- Discussion en ligne : Vendredi  24 mars 2023 de 16h à 18h

- Thématiques abordées : Bases de python, numpy, pandas

- NB : Vous êtes priés d’utiliser Jupyter notebook comme environnement de développement intégré (IDE).Vous pouvez soumettre votre travail en Jupyter notebook ou en htlm. 


# Partie 1 : Bases de python (chaque question est notée sur 5pts)

In [2]:
# 1.Déclarer les variables x, y et z respectives suivantes dans votre IDE : 2, 4.3 et https://raw.githubusercontent.com/pefura/IFPERA/main/Base%20_pleuresie_ML_2.csv
x= 2
y = 4.3
z = "https://raw.githubusercontent.com/pefura/IFPERA/main/Base%20_pleuresie_ML_2.csv"

In [3]:
x/y

0.46511627906976744

In [5]:
# 2.Calculer x/y, x-2y.
print("x/y =", x/y)
print("x-2y =", x-2*y)

x/y = 0.46511627906976744
x-2y = -6.6


In [3]:
# 3.Déterminer la partie entière de la division de y par x.
print("Déterminer la partie entière de la division de y par x:", y//x)

Déterminer la partie entière de la division de y par x: 2.0


In [4]:
# 4. Déterminer le reste de la division de y par x.
print("Déterminer le reste de la division de y par x:", y%x)

Déterminer le reste de la division de y par x: 0.2999999999999998


In [7]:
# 5.En utilisant une fonction native précise de python, créer la liste nommée « List » de tous les éléments de z séparés par « / ».
List = z.split("/")
List

['https:',
 '',
 'raw.githubusercontent.com',
 'pefura',
 'IFPERA',
 'main',
 'Base%20_pleuresie_ML_2.csv']

In [8]:
len(List)

7

In [9]:
# 6.Extraire l’élément en deuxième position de « List ».
List[1]

''

In [10]:
# 7.Supprimer l’élément « ' ' » de la liste « List ».
List.remove('')
List

['https:',
 'raw.githubusercontent.com',
 'pefura',
 'IFPERA',
 'main',
 'Base%20_pleuresie_ML_2.csv']

In [11]:
# 8. Extraire le dernier élément de « List ».
List[-1]

'Base%20_pleuresie_ML_2.csv'

In [12]:
# Avant dernier élement de la liste
List[-2]

'main'

In [13]:
# Choisir les éléments situés entre l'index 0 et 2(exclu)
List[0:2]

['https:', 'raw.githubusercontent.com']

In [17]:
# 9.Construire un dictionnaire nommé « dict » avec les clés suivantes : oiseau, chat, chien. 
# Les valeurs de ces clés étant la traduction anglaise des clés. 

dictionnaire = {"oiseau":"bird",
                "chat":"cat", 
               "chien":"dog" 
              }
dictionnaire

{'oiseau': 'bird', 'chat': 'cat', 'chien': 'dog'}

In [81]:
len(dictionnaire)

3

# Partie 2 : Numpy (chaque question est notée sur 5pts)
Déclarer les objets suivants (poids en kg, taille en cm et sexe [1= sexe masculin, 2 = sexe féminin]):

poids= [50, 55, 80, 70, 86, 64]

taille = [157, 170, 170, 162, 171, 148]

sexe  = (1, 2, 2, 2, 1, 1)


In [ ]:
poids= [50, 55, 80, 70, 86, 64]
taille = [170, 170, 170, 162, 171, 148]
sexe  = (1, 2, 2, 2, 1, 1)

In [24]:
# 10.Comment appelle-t-on les structures de données utilisées pour chacun des objets poids, taille et sexe définis dans la vignette de la partie 2 dans python
# (dresser dans votre IDE simplement un tableau contenant les réponses)?  
import pandas as pd
pd.DataFrame([{"poids": "list", "taille": 'list', "sexe": "tuple"}], index = ['Séquences']).T

Séquences
poids       list
taille      list
sexe       tuple

In [1]:
import numpy as np

In [25]:
# 11.En utilisant la librarie numpy [Numerical Python], 
# transformer les objets poids, taille, sexe en  tableaux numpy de dimension 1 (1 D array).
poids_np = np.array(poids)
taille_np = np.array(taille)
sexe_np = np.array(sexe)
poids_np,taille_np,sexe_np

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

(array([50, 55, 80, 70, 86, 64]),
 array([170, 170, 170, 162, 171, 148]),
 array([1, 2, 2, 2, 1, 1]))

In [26]:
poids_np.ndim # dimension des tables crées

1

In [35]:
# 12.Créer une matrice (mat) numpy dont les objets poids, taille et sexe sont des colonnes. 
mat = np.array([poids, taille, sexe]).T # noter l'utilsisation de la= méthode transpose (T)
mat

<IPython.core.display.Javascript object>

array([[ 50, 170,   1],
       [ 55, 170,   2],
       [ 80, 170,   2],
       [ 70, 162,   2],
       [ 86, 171,   1],
       [ 64, 148,   1]])

In [36]:
# 13. Quelle est la  forme de « mat » ?
np.shape(mat)# 6 lignes et 3 colonnes

<IPython.core.display.Javascript object>

(6, 3)

In [37]:
mat.shape

(6, 3)

# Partie 3 : Pandas (chaque question est notée sur 5pts)

In [33]:
import pandas as pd

In [38]:
# 14.Transformer mat en un dataframe de pandas nommé « dataset » 
# en indiquant clairement le nom des colonnes. 
dataset = pd.DataFrame(mat, columns = ("poids", "taille", "sexe"))
dataset 

poids  taille  sexe
0     50     170     1
1     55     170     2
2     80     170     2
3     70     162     2
4     86     171     1
5     64     148     1

In [112]:
# 15.Sélectionner la sous-base « dataset_female » de dataset ne contenant que les sujets de sexe féminin. 

dataset_female = dataset[dataset["sexe"]==2]
dataset_female 

poids  taille  sexe
1     55     170     2
2     80     170     2
3     70     162     2

In [49]:
data = dataset[["poids", "taille"]]
data

poids  taille
0     50     170
1     55     170
2     80     170
3     70     162
4     86     171
5     64     148

# Partie 4 : Fonctions 

In [40]:
# 16.En utilisant la boucle for, créer une liste contenant 
# les logarithmes naturels des éléments de la liste « poids » définie à la partie 2 (10 pts). 
log_poids = [] # Créer d'abord une liste vide
for i in poids:
    log_i=np.log(i) # calcul du log des différents poids
    log_poids.append(log_i)# Attacher chaque log de poids à la liste vide
print(log_poids)# imprimer les résulats

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[3.912023005428146, 4.007333185232471, 4.382026634673881, 4.248495242049359, 4.454347296253507, 4.1588830833596715]


In [46]:
# 17.Définissez une fonction générique nommée « obesity_classification » qui permet à partir 
# du poids et de la taille d’un individu de déterminer s’il est maigre, de poids normal, 
# en surpoids ou obèse. Il est nécessaire d’utiliser l’indice de masse corporelle (IMC) 
# avec les cut-off suivants 18.5 kg/m2, 26 kg/m2 et 30 kg/m2 pour définir respectivement 
# les classes d’IMC. Il est également conseiller d’afficher la classe correspondante 
# avec l’IMC correspondant (10 pts). 

def obesity_classification (poids,taille):
    # poids en kg et taille en m
    IMC = poids/(taille*taille)
    print("Indice de masse corporelle (kg/m2):",IMC) # imprimer à l'écran l'IMC en kg/m2
    # Utiliser les instructions conditionnelles pour classer l'IMC
    if IMC < 18.5:
        print("obesity_classification:", "maigreur")
    elif IMC >= 18.5 and IMC < 26:
        print("obesity_classification:", "poids normal")
    elif IMC >= 26 and IMC < 30:
        print("obesity_classification:", "surpoids")
    else:
        print("obesity_classification:", "obèse")
        

In [47]:
# 18.Exécuter la fonction « obesity_classification » pour les deux premières observations de dataset (question 14), 5 pts. 

print("observation 1:")
obesity_classification (poids=50,taille=1.70)

print("observation 2:")
obesity_classification (poids=55,taille=1.70)

observation 1:
Indice de masse corporelle (kg/m2): 17.301038062283737
obesity_classification: maigreur
observation 2:
Indice de masse corporelle (kg/m2): 19.031141868512112
obesity_classification: poids normal
